### ISSUE TITLE
Reference 没有实现么？

### ISSUE THREAD

**Issue by ganyao114** [digitalgust/miniJVM#1]

**Comment by digitalgust** [comment]
目前还没有实现不同类型的 Reference  类型,如果是 cache 类型的应用,可以先考虑LinkedHashMap来作为cache. 我后面会考虑实现Reference, 但这个会一定程度上影响垃圾回收的效率, 因为这是个解释型jvm. 所以一切以快为目标.

**Comment by digitalgust** [comment]
Reference supported now
