### ISSUE TITLE
GUI problem

### ISSUE THREAD

**Issue by drthinh** [digitalgust/miniJVM#4]
The start up GUI crashed in Android 10, Windows 10 x64. It showed empty when change language.

**Comment by drthinh** [comment]
The start-up is a really issue, it crashed with all platforms especially android version. I don't have guide/tutorial about GUI api so could not repair or write another GUI app to demonstrate.
To compile new app, I only use your attached janio compiler, it didnt show any error message so I dont know where is the problem, trying to use trial error method is so wasting time. I hope you will have solutions for it. Thank you

**Comment by digitalgust** [comment]
I missed submit gui lib binary, and there is an error in StandalongGuiAppClassLoader , so the win platform can't find the startup class.
I have fixed these two errors.
