### ISSUE TITLE
Suggest moving out binary release.

### ISSUE THREAD

**Issue by Pursuer2** [digitalgust/miniJVM#5]
Tracking these binary file make git fetch slow and enlarge the size of repository. 
Puting binary release to Github Release maybe better.

**Comment by digitalgust** [comment]
Ok, i will remove the binary file out of the repository.

**Comment by digitalgust** [comment]
remove binary files from reposity and all of histories.
released the last version.
thanks for your suggest.

**Comment by Pursuer2** [comment]
your are welcome.
