### ISSUE TITLE
'mbedtls/config.h' file not found

### ISSUE THREAD

**Issue by orange451** [digitalgust/miniJVM#6]
I opened the test ios project in xcode on two of my laptops. This error is in almost every class:
`"'mbedtls/config.h' file not found"`
when trying to import:
`#include "mbedtls/config.h"`

**Comment by orange451** [comment]
Also: 你有没有微信？可以加一下

**Comment by digitalgust** [comment]
微信号 30600449

**Comment by digitalgust** [comment]
![截屏2020-11-19 下午6 18 26](https://user-images.githubusercontent.com/19265420/99653246-bfb80780-2a93-11eb-8b8d-170731193eb5.png)
maybe you can setup user header search path

**Comment by orange451** [comment]
This worked. Thank you!
